### ISSUE TITLE
数据库migrate 非空依赖报错

### ISSUE THREAD

**Issue by jnuc093** [huanghua581/dingo-api-demo#1]
php artisan migrate
php artisan db:seed
时候有为空报错我把相关字段设置为nullable就OK了:
            $table->nullableTimestamps('created_at');
            $table->nullableTimestamps();

**Comment by jnuc093** [comment]
别忘了执行 composer up

**Comment by jnuc093** [comment]
// 短信密钥
    protected $smsApiKey = '';

**Comment by huanghua581** [comment]
👍
